name:                skat-engine
version:             0.1.0.0
github:              "dandro/skat-engine"
license:             BSD3
author:              "dnlmrtnz"
maintainer:          "dandro.dsign@gmail.com"
copyright:           "2021 Daniel Martinez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/skat-engine#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.15.1
- hspec >= 2.7.8
- pathtype >= 0.8.1
- directory >= 1.3.6
- containers >= 0.4.0
- bytestring >= 0.10.12
- text >= 1.2.4
- aeson >= 1.5.6
- wizards >= 1.0.3
- haskeline >= 0.8.1

library:
  source-dirs: src

executables:
  skat-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - skat-engine

tests:
  skat-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - skat-engine
